-- Basic coding (Treesitter Standard)
vim.api.nvim_set_hl(0, "@keyword.directive", {fg = "LightBlue"}) -- replaces @preproc
vim.api.nvim_set_hl(0, "@keyword", {fg = "DeepPink"})
vim.api.nvim_set_hl(0, "@type", {fg = "Cyan"})
vim.api.nvim_set_hl(0, "@type.builtin", {fg = "Cyan"})
vim.api.nvim_set_hl(0, "@function", {fg = "White"})
vim.api.nvim_set_hl(0, "@function.method", {fg = "White"})
vim.api.nvim_set_hl(0, "@comment", {fg = "SteelBlue"})
vim.api.nvim_set_hl(0, "@variable", {fg = "White"}) -- Ensure variables aren't greyed out
vim.api.nvim_set_hl(0, "@variable.parameter", {fg = "White"})

vim.api.nvim_set_hl(0, "LineNr", {fg = "SteelBlue"})
vim.api.nvim_set_hl(0, "CursorLineNr", {fg = "SteelBlue"})
vim.api.nvim_set_hl(0, "@character", {fg = "Lavender"})
vim.api.nvim_set_hl(0, "@constant", {fg = "Plum"})
vim.api.nvim_set_hl(0, "@constant.builtin", {fg = "Plum"})
vim.api.nvim_set_hl(0, "@string", {fg = "Thistle"})
vim.api.nvim_set_hl(0, "@number", {fg = "Violet"})
vim.api.nvim_set_hl(0, "@number.float", {fg = "Violet"})
vim.api.nvim_set_hl(0, "@module", {fg = "LightBlue"}) -- replaces @namespace

vim.api.nvim_set_hl(0, "Search", {fg = "Black", bg = "LightBlue"})
vim.api.nvim_set_hl(0, "IncSearch", {fg = "Black", bg = "LightBlue"})
vim.api.nvim_set_hl(0, "ColorColumn", {bg = "#101020"})
vim.api.nvim_set_hl(0, "Normal", {bg = "#000510", fg = "White"})

-- LSP Semantic Tokens (This ensures LSP doesn't break your colors)
vim.api.nvim_set_hl(0, "@lsp.type.class", {link = "@type"})
vim.api.nvim_set_hl(0, "@lsp.type.decorator", {link = "@function"})
vim.api.nvim_set_hl(0, "@lsp.type.function", {link = "@function"})
vim.api.nvim_set_hl(0, "@lsp.type.method", {link = "@function.method"})
vim.api.nvim_set_hl(0, "@lsp.type.macro", {fg = "Orchid"})
vim.api.nvim_set_hl(0, "@lsp.type.parameter", {link = "@variable.parameter"})
vim.api.nvim_set_hl(0, "@lsp.type.variable", {link = "@variable"})

-- UI (Floating window)
vim.api.nvim_set_hl(0, "FloatBorder", {fg = "LightBlue"})
vim.api.nvim_set_hl(0, "NormalFloat", {fg = "Thistle"})

-- UI (Neo-tree)
vim.api.nvim_set_hl(0, "NeoTreeNormal", {bg = "Black", fg = "White"})
vim.api.nvim_set_hl(0, "NeoTreeRootName", {fg = "SteelBlue"})
vim.api.nvim_set_hl(0, "NeoTreeDirectoryName", {fg = "LightBlue"})
vim.api.nvim_set_hl(0, "NeoTreeDirectoryIcon", {fg = "Lightblue"})
vim.api.nvim_set_hl(0, "NeoTreeFileNameOpened", {fg = "Violet"})
vim.api.nvim_set_hl(0, "NeoTreeFileIcon", {fg = "Violet"})
vim.api.nvim_set_hl(0, "NeoTreeGitModified", {fg = "DeepPink"})
vim.api.nvim_set_hl(0, "NeoTreeGitStaged", {fg = "White"})
vim.api.nvim_set_hl(0, "NeoTreeGitUntracked", {fg = "DeepPink"})

-- UI (Snacks Dashboard)
vim.api.nvim_set_hl(0, "SnacksDashboardIcon", {fg = "Cyan"})
vim.api.nvim_set_hl(0, "SnacksDashboardDesc", {fg = "White"})
vim.api.nvim_set_hl(0, "SnacksDashboardKey", {fg = "DeepPink"})

-- UI (fzf-lua)
vim.api.nvim_set_hl(0, "FzfLuaBorder", {link = "FloatBorder"})
vim.api.nvim_set_hl(0, "FzfLuaTitle", {link = "FloatBorder"})
vim.api.nvim_set_hl(0, "FzfLuaFzfMatch", {fg = "Thistle"})
