--basic coding
vim.api.nvim_set_hl(0, "@preproc", {fg = "LightBlue"})
vim.api.nvim_set_hl(0, "@keyword", {fg = "DeepPink"})
vim.api.nvim_set_hl(0, "@type", {fg = "Cyan"})
vim.api.nvim_set_hl(0, "@function", {fg = "White"})
vim.api.nvim_set_hl(0, "@type.builtin", {fg = "Cyan"})
vim.api.nvim_set_hl(0, "@comment", {fg = "SteelBlue"})
vim.api.nvim_set_hl(0, "LineNr", {fg = "SteelBlue"})
vim.api.nvim_set_hl(0, "CursorLineNr", {fg = "SteelBlue"})
vim.api.nvim_set_hl(0, "@character", {fg = "Lavender"})
vim.api.nvim_set_hl(0, "@constant", {fg = "Plum"})
vim.api.nvim_set_hl(0, "@string", {fg = "Thistle"})
vim.api.nvim_set_hl(0, "@number", {fg = "Violet"})
vim.api.nvim_set_hl(0, "@macro", {fg = "Orchid"})
vim.api.nvim_set_hl(0, "Search", {fg = "Black", bg = "LightBlue"})
vim.api.nvim_set_hl(0, "IncSearch", {fg = "Black", bg = "LightBlue"})
vim.api.nvim_set_hl(0, "ColorColumn", {bg = "DimGrey"})
vim.api.nvim_set_hl(0, "Normal", {bg = "Black", fg = "White"})
--ui (regular floating window)
vim.api.nvim_set_hl(0, "FloatBorder", {fg = "LightBlue"})
vim.api.nvim_set_hl(0, "NormalFloat", {fg = "Thistle"})
--ui (Neotree)
vim.api.nvim_set_hl(0, "NeoTreeNormal", {bg = "Black"})
vim.api.nvim_set_hl(0, "NeoTreeNormal", {fg = "White"})
vim.api.nvim_set_hl(0, "NeoTreeRootName", {fg = "SteelBlue"})
vim.api.nvim_set_hl(0, "NeoTreeDirectoryName", {fg = "LightBlue"})
vim.api.nvim_set_hl(0, "NeoTreeDirectoryIcon", {fg = "Lightblue"})
vim.api.nvim_set_hl(0, "NeoTreeFileNameOpened", {fg = "Violet"})
vim.api.nvim_set_hl(0, "NeoTreeFileIcon", {fg = "Violet"})
vim.api.nvim_set_hl(0, "NeoTreeGitModified", {fg = "DeepPink"})
vim.api.nvim_set_hl(0, "NeoTreeGitStaged", {fg = "White"})
vim.api.nvim_set_hl(0, "NeoTreeGitUntracked", {fg = "DeepPink"})
vim.api.nvim_set_hl(0, "NeoTreeSeparatorActive", {fg = "Thistle"})
vim.api.nvim_set_hl(0, "NeoTreeSeparatorInactive", {fg = "Thistle"})
vim.api.nvim_set_hl(0, "NeoTreeDimText", {fg = "White"})
--ui (Dashboard)
vim.api.nvim_set_hl(0, "SnacksDashboardIcon", {fg = "Cyan"})
vim.api.nvim_set_hl(0, "SnacksDashboardDesc", {fg = "White"})
vim.api.nvim_set_hl(0, "SnacksDashboardKey", {fg = "DeepPink"})
--ui (fzf-lua)
vim.api.nvim_set_hl(0, "FzfLuaBorder", {link = "FloatBorder"})
vim.api.nvim_set_hl(0, "FzfLuaTitle", {link = "FloatBorder"})
vim.api.nvim_set_hl(0, "FzfLuaPreviewBorder", {link = "FloatBorder"})
vim.api.nvim_set_hl(0, "FzfLuaPreviewTitle", {link = "FloatBorder"})
vim.api.nvim_set_hl(0, "FzfLuaFzfMatch", {fg = "Thistle"})
